echo "services:
  - type: web
    name: tstorage
    env: node
    rootDir: .
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: tstorage-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production" > render.yaml